### ISSUE TITLE
Connecting TO ATP

### ISSUE THREAD

**Issue by Owais928** [daust/JasperReportsIntegration#110]
Check 4: Can we talk to the J2EE server?
Error occured: ORA-29273: HTTP request failed ORA-06512: at "SYS.HTTPURITYPE", line 38 ORA-29024: Certificate validation failure ORA-06512: at "SYS.UTL_HTTP", line 380 ORA-06512: at "SYS.UTL_HTTP", line 1209 ORA-06512: at "SYS.HTTPURITYPE", line 23

We couldn't make a successful connection to https://example:443.

This can be ignored when the other tests are successful. Sometimes the J2EE server doesn't have a working index page (mostly for security reasons).

Please make sure:
The J2EE server is up and accepting connections
The firewalls allow the communication from the database to the J2EE server (if not installed locally)

While Testing with Oracle Autonomous Database (ATP) getting this issue. I have granted the ACL's too but same.
i have replaced the url with https://example:443 my actual url is using https as i have enabled ssl on tomcat.
Kindly share solution if you have.
Thanks & Regards
![github_issue](https://user-images.githubusercontent.com/87062256/169970873-df796a2f-d277-4e16-956c-b4ebf0c6e6c7.jpg)

**Comment by daust** [comment]
This is a common problem when you connect to a site using HTTPS but have not set up the wallet correctly. 
I will close the ticket because it is not an issue with the code. 

If you need further assistance, please post your request in the forum: https://gitq.com/daust/JasperReportsIntegration. 
Best
~Dietmar.
