### ISSUE TITLE
When using jasper report Integration sessions are not closed propperly

### ISSUE THREAD

**Issue by dennisverdaasdonk** [daust/JasperReportsIntegration#20]
We are using the new version of the inegration and we have at the end of the day many open connections.
we need a fix for this

**Comment by PeterPSSE** [comment]
Hi, I have the same problem here at a customer site and reported this to Dietmar on Oct. 22nd of '18. Before the update of JRI 2.4.x.x to 2.5.0.1 everything was fine. Since he was very busy at this time, I wrote a database "cron job" that killed all inactive JasperReport sessions from time to time (once every hour). This is a workaround, but far better than crashing the database.

**Comment by Geri1590** [comment]
Same here. We're having problems with this issue on Linux environments (connections don't close), and Windows as well.
Issue in Windows is a bit different, because the connections do not appear on netstat, but after a whole day, the Windows internal ports may exhaust, and Tomcat triggers something like "no more ports available" exception when trying to stablish a connection. Then all crashes.
I'm surprised because it seems this is only happening to a very few people. Maybe it is because the Tomcat version? I have Tomcat 9 on Windows 10, and Tomcat 7 on linux.
This is driving us crazy :S

**Comment by joeph** [comment]
Same problem here, idle connections keep adding up.

**Comment by Geri1590** [comment]
Some screenshots of the "waiting" sessions that generate:

![image](https://user-images.githubusercontent.com/2327821/67755175-f447c400-fa37-11e9-9bf2-30160f31affc.png)

![image](https://user-images.githubusercontent.com/2327821/67755199-0295e000-fa38-11e9-9f52-00abe4469e65.png)

![image](https://user-images.githubusercontent.com/2327821/67755257-20fbdb80-fa38-11e9-8ad5-7e820192ec2c.png)

**Comment by kuldeepsidhu88** [comment]
@daust  Is this project actively maintained? Can you please clarify?

**Comment by daust** [comment]
Hi guys, will spend some time on these issues next week.

**Comment by daust** [comment]
This is fixed in the upcoming release 2.6.0. I have upgraded to ojdbc8.jar with support for Oracle 19.7 and also implemented the Oracle UCP (Universal Connection Pool).

**Comment by joeph** [comment]
Great, thank you!

**Comment by Geri1590** [comment]
This is very good news. Thanks!
