### ISSUE TITLE
Variable for report path

### ISSUE THREAD

**Issue by AljazMaliTRTS** [daust/JasperReportsIntegration#84]
Hi Dietmar, 

it would be great if there would be a dedicated setting/variable that would allow to specify the location of reports.

Thank you,
Aljaž

**Comment by daust** [comment]
As discussed, I can implement this using a path setting in the ``application.properties`` file, something like this: 
```
reportsPath=reports:/path/to/reports1:/path/to/reports2:/path/to/reports3
```
and for Windows: 
```
reportsPath=reports;c:\\path\\to\\reports1;c:\\path\\to\\reports2;c:\\path\\to\\reports3
```

- an exception will be raised when one of the paths cannot be found
- in order to locate a report, all report paths will be processed in order, testing for the file. 
- the default setting will reflect the current implementation, i.e. ``reportsPath=reports``
- this path ``reports`` will be relative to the configuration-directory (resolved either through ${OC_JASPER_CONFIG_HOME} or the setting in the web.xml file.

**Comment by AljazMaliTRTS** [comment]
Great, thank you! 

Aljaž

**Comment by daust** [comment]
We have a new section in the ``application.properties`` file: 
```
# report definition files will be looked up in the following order as
#   specified by the reportsPath, e.g.: 
#     Linux/macOS: reportsPath=../reports,/path/to/reports1:/path/to/reports2:/path/to/reports3
#     Windows: reportsPath=..\\reports;c:\\path\\to\\reports1;c:\\path\\to\\reports2;c:\\path\\to\\reports3
#   If the reportsPath is left empty or not defined, then the default is "../reports" (*nix) or
#      "..\\reports" (windows) respectively, will start from the location of the application.properties (this)
#      file
reportsPath=
```

The documentation is updated as well, the ``installation-full.md`` and ``README.md`` files.
