### ISSUE TITLE
Issue with PDF download - network error

### ISSUE THREAD

**Issue by octavarium12** [daust/JasperReportsIntegration#92]
Hi I am  using Jasperreportsintegration 2.7 with cloud database , I cant download pdf to my pc or mobile . Its Failed -network error problem.
I tried different browser.
When I turn option in Jasper Procedure to  download PDF without preview than I have no problem. Only when downloading from preview window.
How to debug this problem
Thanks

**Comment by daust** [comment]
More details, please. What is the exact error? Screenshot? 

When you open the developer toolbar in the browser you can get more details. 
![image](https://user-images.githubusercontent.com/4840057/149948625-c8d1a84f-1428-4ae8-957f-4ea70775043a.png)

**Comment by octavarium12** [comment]
> More details, please. What is the exact error? Screenshot?
> 
> When you open the developer toolbar in the browser you can get more details. ![image](https://user-images.githubusercontent.com/4840057/149948625-c8d1a84f-1428-4ae8-957f-4ea70775043a.png)
@daust 
Thanks for info, I captured this :
![screen2](https://user-images.githubusercontent.com/97959822/149953150-58e0110e-bf34-45f9-a2d5-442a40a00dcf.JPG)
When i click to download pdf to my pc i got this error 
![snipe1](https://user-images.githubusercontent.com/97959822/149953357-183784c1-2ab4-4b24-93e3-0770e93bbe96.JPG)



This is my built in process code in Apex:

```
declare
  l_additional_parameters varchar2(5000);
  verija number;
begin
utl_http.set_wallet('');
  -- set the url for the j2ee application
  -- better retrieve that from a configuration table
  bmt.xlib_jasperreports.set_report_url('https://ccc.com/jri/report');
 
 l_additional_parameters := 'p_p='||apex_util.url_encode(:P226_NEW_11);
 
  bmt.xlib_jasperreports.show_report (p_rep_name => 'report123',
                                  
                             p_rep_format => 'pdf',  
                                  p_data_source => 'default',  
                                --  p_rep_locale => 'en_US',  
                              --    p_rep_encoding => 'UTF-8',
                      --  p_out_filename        => 'Karton_radnika.pdf',
                                  
                      -- p_save_is_enabled  =>  true,
                         --  p_save_filename      =>  'testt'        
                                  p_additional_params => l_additional_parameters
                                  );

 
  -- stop rendering of the current APEX page
  apex_application.g_unrecoverable_error := true;
 
end;
```
I can preview PDF but cant download it.

**Comment by daust** [comment]
Hi, 

a quick search on google (or DuckDuckGo for that matter ;) leads to antivirus software blocking it locally on your PC: https://duckduckgo.com/?q=browser+download+%22Failed+-+Network+error%22&atb=v221-1&ia=web

Seems to be unrelated to JRI. 

Can you try some of the suggestions ?  Does it work? 

Best
~Dietmar.

**Comment by octavarium12** [comment]
@daust thanks for advice,  I tried to disable antivirus, also I tried it on different pc - s and on mobile. Its same error on every device. I tried all browsers.
Also direct downloading without preview is working so its not about folder or drive rights or policies. Its some strange bug , I had same problem on 2.4 version.

**Comment by daust** [comment]
Best to have a personal look at it. Please send me an email to dietmar.aust at opal-consulting.de, then we can schedule a zoom call.

**Comment by octavarium12** [comment]
Sure, I will send e-mail. Thank you

**Comment by octavarium12** [comment]
Hi @daust . I use option 1, also I use  redirect on another page with same logic for my direct printing from link on interactive reports. Mostly there is no need for my reports to be previewed before downloading  and for those specific one this is solution. I will experiment more with PDF viewers and stuff. Should I close Issue now ?

Thank you for your time
Haris.

**Comment by daust** [comment]
Yes, close the issue, please. Especially, since it is not related to the integration per se. It is an issue of how the internal pdf viewer in Google Chrome handles the pdf-"file", which is not really a file on the backend server but rather a post request. 

Actually, you don't even have to use a separate page. 

I often put it on the same page (so the application logic is not cluttered on too many pages) by making the rendering pl/sql process conditional to a certain request value, e.g. I use "RUN_REPORT" as an example. You can choose any kind of request variable that you want. 

![image](https://user-images.githubusercontent.com/4840057/150486966-58b3d9fe-939d-43ab-9bc0-bd53c1f3b669.png)

So the process will NOT be rendered initially. 

You submit button on will do nothing on the processing side. It will ONLY activate the branch, which will go to the SAME page (5) and issue the request RUN_REPORT: 
![image](https://user-images.githubusercontent.com/4840057/150487660-d245feb2-b2cd-43b3-baf6-fdcee0c1bfda.png)

This time, the page will be re-rendered, and the process is being run because the condition is met this time. 

This way, the application logic is on the same page and easy to understand. 

Best
~Dietmar.

**Comment by octavarium12** [comment]
@daust   Yes but this is parameter form,  I get empty report because parameter value is lost after I branch on same site.

**Comment by daust** [comment]
Sure, no big deal. 

Just pass it along in the branch like you would always do it: 
![image](https://user-images.githubusercontent.com/4840057/150533618-956d0858-49f9-485d-9b04-cc52a6269924.png)

**Comment by octavarium12** [comment]
@daust Process fire before header and cant get that parameter value ,parameter  item is in region so i get empty report
